version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinelapi
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: